services:
  evm-mcp:
    image: tolak/evm-mcp-server:v0.1.0
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - EVM_PRIVATE_KEY=${EVM_PRIVATE_KEY}
      - RPC_URL=${RPC_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - COINGECKO_PRO_API_KEY=${COINGECKO_PRO_API_KEY}
    restart: unless-stopped